# Configuration file for ARDE Model

# Folder where user will put downloaded / raw rainfall data
data_dir: "D:\\ARDE-Model-main\\data"

# Folder where processed results, plots, and outputs will be saved
output_dir: "D:\\ARDE-Model-main\\output"

# Station details (optional, can be changed by user)
station_name: "Roorkee"
lat: 29.88
lon: 77.8975

# Date range for data extraction
start_date: "2024-01-01"
end_date: "2024-12-31"

# CDS API credentials
cds_url: "https://cds.climate.copernicus.eu/api"
cds_key: "enter-the-key"

gee_project_id: "enter-the-project-ID"

