# Configuration file for ARDE Model

# Folder where user will put downloaded / raw rainfall data
data_dir: "E:\\ARDE Model\\data"

# Folder where processed results, plots, and outputs will be saved
output_dir: "E:\\ARDE Model\\output"

# Station details (optional, can be changed by user)
station_name: "Murapannadu"
lat: 8.7144
lon: 77.835


start_date: "2022-01-01"  
end_date: "2024-12-31" 
